### PR TITLE
Milestone 2

### PR DESCRIPTION
**Pull request by mariordgez**
In the second milestone, you will create the 3 columns main section of the website for the 3 screen sizes.

    Column 1
        Featured stories
        Sponsored insights / Rankings
    Column 2
        Top story
        My turn
        Culture & travel
        More stories
        Latest news
    Column 3
        The debate
        Opinion
        Sponsored insights / Rankings
        Free signup

### CODE REVIEW

**Comment by mariordgez** [comment]
Please use live server to deploy the page, we are still using github pages on milestone 1, there is still an issue to work on that particular Milestone,  I hope you like the project and have a nice day.

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @mariordgez and @petumazo :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

### The 3 columns main section
 - For each piece of news

    * [x] Each image should have a link. The rounded images in the third column should also have a link
    * [x] Each title uses a hx tag and have a link. Most of the title in the third column does not use a hx tag
* [x] The `MORE STORIES` section should come immediately after `CULTURE & TRAVEL`

Original | Yours
------- | -------
image | image

* [x] Kindly follow the order in the table below for mobile view

| Mobile |
|--------|
| TOP STORY |
| FEATURED STORIES |
| THE DEBATE |
| OPINION |
| SPONSORED INSIGHT |
| MORE STORIES |
| LATEST NEWS |
| MY TURN |
| CULTURE & TRAVEL |
| SPONSORED INSIGHT |
| FREE SIGN UP |
| SPONSORED INSIGHT |





### "As described in the [Code review limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#) you have 2 code reviews left for this project."
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by petudeveloper** [comment]
thank you for your comments. They helped us to clean the code and correct something we were missing.

We did all the suggested changes:
- For each piece of news we added a link to the images.
- We used <h> tags on all the titles of the third column. We also add links to them.
- Correct the order of the sections MORE STORIES and CULTURE & TRAVEL.

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @mariordgez and @1  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

#### Good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
